version: "3"

services: 
    node-app-container:
        image: gaurang98671/auth_service
        ports: 
            - "8080:8080"
        environment:
            - MONGO_USER=gaurang
            - MONGO_PASSWORD=123
            - REDIS_SECRET=secret
        volumes: 
            - ./:/app
        depends_on:
            - mongo

        
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=gaurang
            - MONGO_INITDB_ROOT_PASSWORD=123
        volumes: 
            - mongo-db:/data/db
    
    redis:
        image: redis
volumes: 
    mongo-db:
    myapp: