version: "3"

services: 
    node-app-container:
        image: trainer-image
        ports: 
            - "8080:8080"
        environment:
            - MONGO_USER=gaurang
            - MONGO_PASSWORD=123
        volumes: 
            - ./:/app
        depends_on:
            - mongo
        command: npm run dev
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=gaurang
            - MONGO_INITDB_ROOT_PASSWORD=123
        volumes: 
            - mongo-db:/data/db
        
volumes: 
    mongo-db:
    myapp: