name: Docker Image CI

on:
  push:
    branches: [ main ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gaurang98671/auth_service
      
    - name: Login to docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      
    - name: Push to docker hub
      run: docker push gaurang98671/auth_service
